services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - app-network

  users:
    build: ./users
    container_name: users
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3001"
    networks:
      - app-network
    
  posts:
    build: ./posts
    container_name: posts
    restart: always
    depends_on:
      - postgres
      - users 
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3002:3002"  
    networks:
      - app-network

  comments:
    build: ./comments
    container_name: comments
    restart: always
    depends_on:
      - postgres
      - posts
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3003:3003"
    networks:
      - app-network


volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
